CREATE OR REPLACE CORTEX SEARCH SERVICE NEWS_DB.GOLD.SEARCH_SERVICE_NOTICIAS
ON CHUNK
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 day'
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
    SELECT * FROM NEWS_DB.GOLD.NOTICIAS_CHUNK
);