CREATE OR REPLACE STAGE s3_json_landing_bucket
URL='s3://ev-dr-landing/'
FILE_FORMAT=(
    TYPE=JSON
    STRIP_NULL_VALUES=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    STRIP_OUTER_ARRAY=TRUE
)
CREDENTIALS=(
    AWS_KEY_ID=''
    AWS_SECRET_KEY=''
);